my_annotation('[Agriculture.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Agriculture.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Agriculture.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Agriculture.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Agriculture.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Agriculture.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment existing hous\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment existing hous\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment existing hous\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment existing hous\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment existing hous\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment existing hous\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment new houses\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment new houses\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment new houses\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment new houses\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment new houses\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment new houses\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment public buildi\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment public buildi\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Built environment public buildi\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment public buildi\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Built environment public buildi\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Built environment public buildi\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Chemical industry\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Chemical industry\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Chemical industry\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Chemical industry\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Chemical industry\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Chemical industry\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Diverse gegevens\'.B9:B23]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Diverse gegevens\'.B30:B32]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Diverse gegevens\'.B50:B58]',skos:broadMatch,agro:c_16121,ground_truth).%[Energy consumption]
my_annotation('[\'Diverse gegevens\'.B71:B73]',skos:broadMatch,agro:c_16121,ground_truth).%[Energy consumption]
my_annotation('[\'Diverse gegevens\'.C48:E48]',skos:broadMatch,agro:c_331377,ground_truth).%[emission]
my_annotation('[\'Diverse gegevens\'.J71:J72]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Diverse gegevens\'.K48:K50]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Diverse gegevens\'.M47:P47]',skos:broadMatch,agro:c_16121,ground_truth).%[Energy consumption]
my_annotation('[\'Diverse gegevens\'.R78:X78]',skos:broadMatch,agro:c_331377,ground_truth).%[emission]
my_annotation('[\'Electricity production\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Electricity production\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Electricity production\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Electricity production\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Electricity production\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Electricity production\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Electricity storage\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Electricity storage\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Electricity storage\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Electricity storage\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Electricity storage\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Electricity storage\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Fertilizer.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Fertilizer.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Fertilizer.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Fertilizer.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Fertilizer.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Fertilizer.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Hydrogen.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Hydrogen.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Hydrogen.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Hydrogen.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Hydrogen.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Hydrogen.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Individual cars\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Individual cars\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Individual cars\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Individual cars\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Individual cars\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Individual cars\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Industry heat production\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Industry heat production\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Industry heat production\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Industry heat production\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Infrastructure.B25:B27]',skos:broadMatch,agro:c_1922,ground_truth).%[Costs]
my_annotation('[\'Liquid fuels\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Liquid fuels\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Liquid fuels\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Liquid fuels\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Liquid fuels\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Liquid fuels\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Methane gas\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Methane gas\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Methane gas\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Methane gas\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Methane gas\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Methane gas\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Steel.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Steel.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Steel.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Steel.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Steel.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Steel.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Supplies.C39:C50]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Supplies.F38:U38]',skos:broadMatch,agro:c_16121,ground_truth).%[Energy consumption]
my_annotation('[Supplies.W8:W32]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Supplies.W8:W32]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Supplies.W39:W50]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Supplies.W60:W84]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Supplies.W60:W84]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Supplies.W93:W104]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Supplies.AC39:AC51]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Supplies.AG93:AG117]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Supplies.AG93:AG117]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Trucking.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Trucking.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[Trucking.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Trucking.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[Trucking.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[Trucking.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Urban traffic\'.E248:E447]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Urban traffic\'.E248:E447]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
my_annotation('[\'Urban traffic\'.E462:E474]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Urban traffic\'.AO101:AO112]',skos:broadMatch,agro:c_50146,ground_truth).%[Renewable bioresources]
my_annotation('[\'Urban traffic\'.AQ18:AQ67]',skos:broadMatch,agro:c_24056,ground_truth).%[Non renewable resources]
my_annotation('[\'Urban traffic\'.AQ18:AQ67]',skos:broadMatch,agro:c_2570,ground_truth).%[Energy sources]
