% (+ lucht,
% scheep en other),
%,
%* unit en cost aangepast,
%#DIV/0!,
%#REF!,
%loss + renewable gas
%my_t_mapping(literal(' (3 * 25 A)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (alleen ja of nee)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (exclusief alleen doorvoer)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (solide lijst)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (voor alle banden)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (voor alle inputs)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal(' (voor alle outputs)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('-'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('?'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('***'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('aan extra supply'),skos:relatedMatch,agro:c_25122,ground_truth).%[Energy production]
%my_t_mapping(literal('available'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('avoided'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Band 1'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Band 2'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Band 3'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('bij max inzet'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Blok 1: choices gemaakt door de useer'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Blok 2: omzetting choices naar technology lijst voor calculationen'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('calculationen'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Choice useer'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Cijfers op Basis van mais; veronderstelling dat inzet van andere biomassstromen per PJ redelijk vergelijkbaar blijft'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('compensation bio energy'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution (tot - zon/wind)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution band 1'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution band 2'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution band 3'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution technology'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution zon/wind'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('contribution'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('correctionproces br-->gr'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('data voor'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Dataset 1'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Dataset 2'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Deel demand naar'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('degree van usage'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Dimensie'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('E-Design-v2.19 Juli 2011.xls'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('exceedance'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('extra'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('geen'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('gegevens over het systeem in 2050'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('gegevens over resources'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('gemiddeld (gewogen)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('goal'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('is opgenomen'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Kolom met'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('let op: unit Electricity omgezet van TWh naar PJ en van tonneverrijkt U naar PJ U (4 PJ/tonU)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('M'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Maximale need'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
%my_t_mapping(literal('maximum'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('medium'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('name calculation'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('name'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Niet begrensd (dan 1 invullen)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('niet negatief'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('O'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('onzeker of het allemaal om etheen gaat'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('optimistic'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('other gegevens'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('other'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('overview per Subsystem'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('P'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('part'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('per'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('pessimistic'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('potential'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Production+import-export-loss'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Projectname'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Ref'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Reference  (2009)'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Stroomschema'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Subsystem'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('system part'),skos:related,agro:c_330985,ground_truth).%[systems]
%my_t_mapping(literal('Total'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('tussenbalans'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('unit'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('unlimited'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('use'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('van Total'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('verhoudingsfactor'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('Veronderstelling dat op netherlandsse akkerbouw 20 Mtonne manure direct wordt afgezet'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('verzwaringsfactor'),skos:,agro:c_,ground_truth).%[]
%my_t_mapping(literal('zonder import/export'),skos:,agro:c_,ground_truth).%[]
%my_u_mapping(literal('Euro'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('euro'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('euro/kwh'),skos:relatedMatch,om:kilowatt_hour,ground_truth).%[]
%my_u_mapping(literal('euro/MJ'),skos:relatedMatch,om:megajoule,ground_truth).%[]
%my_u_mapping(literal('Eventueel voor een bandcorrection'),skos:,agro:c_,ground_truth).%[]
%my_u_mapping(literal('in Meuro per …'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('in Meuro/TWh'),skos:relatedMatch,om:kilowatt_hour,ground_truth).%[]
%my_u_mapping(literal('MEuro per'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('Meuro'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('Meuro/…'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('Meuro/PJ'),skos:,om:,ground_truth).%[]
%my_u_mapping(literal('Mtonne CO2 eq/PJ'),skos:relatedMatch,om:joule_per_kilogram,ground_truth).%[]

my_t_mapping(literal(' (of efficiency factor)'),skos:relatedMatch,agro:c_2491,ground_truth).%[Efficiency]
my_t_mapping(literal(' (of efficiencyfactor)'),skos:relatedMatch,agro:c_2491,ground_truth).%[Efficiency]
my_t_mapping(literal('aansluiting'),skos:relatedMatch,agro:c_2519,ground_truth).%[Electricity supplies]
my_t_mapping(literal('acquired outputs'),skos:closeMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('Agriculture industry (restpost)'),skos:relatedMatch,agro:c_49913,ground_truth).%[agricultural practices]
my_t_mapping(literal('Agriculture'),skos:relatedMatch,agro:c_49913,ground_truth).%[agricultural practices]
my_t_mapping(literal('air traffic (allocation netherlands)'),skos:broadMatch,agro:c_231,ground_truth).%[air transport]
my_t_mapping(literal('air traffic bunkers'),skos:closeMatch,agro:c_26165,ground_truth).%[Bunker silos]
my_t_mapping(literal('air traffic'),skos:closeMatch,agro:c_231,ground_truth).%[air transport]
my_t_mapping(literal('animal husbandry'),skos:exactMatch,agro:c_8532,ground_truth).%[animal husbandry]
my_t_mapping(literal('avoided Emission'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Basis demand'),skos:broadMatch,agro:c_2171,ground_truth).%[demand]
my_t_mapping(literal('Basis unit Investment'),skos:broadMatch,agro:c_3930,ground_truth).%[investment]
my_t_mapping(literal('Basis unit Production'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('batteries'),skos:relatedMatch,agro:c_2567,ground_truth).%[Energy conservation]
my_t_mapping(literal('bij 50% lagere demand'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('bij demand vergelijkbaar met 2010'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Biodiesel vegetable oil'),skos:broadMatch,agro:c_35013,ground_truth).%[biodiesel]
my_t_mapping(literal('Biofuel'),skos:exactMatch,agro:c_27465,ground_truth).%[biofuels]
my_t_mapping(literal('Biogas'),skos:exactMatch,agro:c_9262,ground_truth).%[biogas]
my_t_mapping(literal('Biogeen plastic (fractie)'),skos:broadMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('biomass co-firing CCS'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('biomass co-firing'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('Biomass dry'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass fermentation other'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('biomass fermentation'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('biomass gasification CCS'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('biomass gasification small scale'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('biomass gasification'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('biomass gasvormig'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass heater'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('biomass in totale Production'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass liquid'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass not in product'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass not in product//waste'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass solid'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass use per proces'),skos:relatedMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass voor energy algemeen'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('Biomass wet'),skos:broadMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('Biomass'),skos:closeMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('biomass'),skos:closeMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('blast furnace DR CCS'),skos:relatedMatch,agro:c_32675,ground_truth).%[Non food industries]
my_t_mapping(literal('blast furnace DR'),skos:relatedMatch,agro:c_32675,ground_truth).%[Non food industries]
my_t_mapping(literal('blast furnacegas'),skos:broadMatch,agro:c_8306,ground_truth).%[Waste gases]
my_t_mapping(literal('Built env'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('Built environment'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('built environment'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('Bunkers'),skos:closeMatch,agro:c_26165,ground_truth).%[Buker silos]
my_t_mapping(literal('Capital costs'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('car recharging system'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('carbohydrates starch'),skos:closeMatch,agro:c_7369,ground_truth).%[Starch]
my_t_mapping(literal('carbohydrates'),skos:exactMatch,agro:c_1300,ground_truth).%[carbohydrates]
my_t_mapping(literal('carmobile'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('CCS (added to technology )'),skos:closeMatch,agro:c_9613,ground_truth).%[Carbon dioxide fixation]
my_t_mapping(literal('Chemical industry'),skos:relatedMatch,agro:c_1515,ground_truth).%[Chemical industry]
my_t_mapping(literal('chemical plastics'),skos:relatedMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('chemical'),skos:relatedMatch,agro:c_1515,ground_truth).%[Chemical industry]
my_t_mapping(literal('Chemistry'),skos:relatedMatch,agro:c_1522,ground_truth).%[Chemistry]
my_t_mapping(literal('Choice performance'),skos:relatedMatch,agro:c_25788,ground_truth).%[equipment performance]
my_t_mapping(literal('Choice performances technology'),skos:relatedMatch,agro:c_25788,ground_truth).%[equipment performance]
my_t_mapping(literal('CHP biomass liquid CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP biomass liquid'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP biomass solid CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP biomass solid'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP biomass'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP gas CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('CHP gas'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('Co- fermentation'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('Co-fermentation manure'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('co-firing biomass'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('CO2 storage capacity'),skos:relatedMatch,agro:c_9613,ground_truth).%[Carbon dioxide fixation]
my_t_mapping(literal('Coal combustion'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('coal combustion'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('Coal gasification CCS'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('Coal gasification'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('Coal-to-Liquid CCS'),skos:broadMatch,agro:c_34771,ground_truth).%[Liquefaction]
my_t_mapping(literal('Coal-to-Liquid'),skos:broadMatch,agro:c_34771,ground_truth).%[Liquefaction]
my_t_mapping(literal('coal'),skos:exactMatch,agro:c_1693,ground_truth).%[Coal]
my_t_mapping(literal('coarse grid Hydrogen'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Cokesovengas'),skos:broadMatch,agro:c_8306,ground_truth).%[Waste gases]
my_t_mapping(literal('combustion engine H2'),skos:broadMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('combustion'),skos:exactMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('cost bij 50%'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('cost Reference '),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('cost'),skos:exactMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('costs per year'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('costs resources'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('costs Total'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('costs typen biomass'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('costs'),skos:exactMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('cows dairy'),skos:broadMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('cows meat'),skos:broadMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('Crude Oil'),skos:exactMatch,agro:c_10178,ground_truth).%[crude oil]
my_t_mapping(literal('crude oil'),skos:exactMatch,agro:c_10178,ground_truth).%[crude oil]
my_t_mapping(literal('cultivated grass'),skos:closeMatch,agro:c_2832,ground_truth).%[Feed grasses]
my_t_mapping(literal('cultivated wood'),skos:closeMatch,agro:c_8421,ground_truth).%[Wood]
my_t_mapping(literal('dairy cows'),skos:broadMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('data on resources international context'),skos:broadMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('demand (excl wind/zon)'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand electric transport'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand elektrolyse'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand Heat LT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand per technology'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand subsystemen'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand uit Basis set'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('demand'),skos:eaxctMatch,agro:c_2171,ground_truth).%[demand]
my_t_mapping(literal('demandbalans'),skos:relatedMatch,agro:c_2171,ground_truth).%[demand]
my_t_mapping(literal('Diesel oil'),skos:exactMatch,agro:c_34813,ground_truth).%[Diesel oil]
my_t_mapping(literal('Distributie'),skos:exactMatch,agro:c_35773,ground_truth).%[Distribution]
my_t_mapping(literal('dry organic waste'),skos:broadMatch,agro:c_35237,ground_truth).%[Organic wastes]
my_t_mapping(literal('EF Methane'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('EF'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Efficiency'),skos:exactMatch,agro:c_2491,ground_truth).%[Efficiency]
my_t_mapping(literal('Eigen Production/supply'),skos:broadMatch,agro:c_25122,ground_truth).%[Energy production]
my_t_mapping(literal('Eiland (civiel)'),skos:broadMatch,agro:c_7431,ground_truth).%[Storage structures]
my_t_mapping(literal('Electric boiler'),skos:broadMatch,agro:c_28286,ground_truth).%[Boilers]
my_t_mapping(literal('Electric car'),skos:relatedMatch,agro:c_25778,ground_truth).%[Electric motors]
my_t_mapping(literal('Electric heat pumps'),skos:broadMatch,agro:c_24398,ground_truth).%[Heat pumps]
my_t_mapping(literal('Electric power supply'),skos:closeMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('Electricity demand (excl. specifieke processen)'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Electricity demand diensten'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Electricity demand households'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Electricity demand'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Electricity generation'),skos:closeMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('Electricity Production'),skos:closeMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('Electricity production'),skos:closeMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('Electricity storage'),skos:broadMatch,agro:c_2567,ground_truth).%[Energy conservation]
my_t_mapping(literal('Electricity'),skos:exactMatch,agro:c_2518,ground_truth).%[Electricity]
my_t_mapping(literal('electrolysis HT'),skos:broadMatch,agro:c_28352,ground_truth).%[Electrolysis]
my_t_mapping(literal('electrolysis'),skos:exactMatch,agro:c_28352,ground_truth).%[Electrolysis]
my_t_mapping(literal('elevated reservoir'),skos:broadMatch,agro:c_7431,ground_truth).%[Storage structures]
my_t_mapping(literal('Emission Factor plastics'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Emission Factor'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Emission'),skos:closeMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Emissions Agriculture huisanimals'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Emissions'),skos:closeMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('energy -inhoud etheen'),skos:broadMatch,agro:c_10607,ground_truth).%[Energy content]
my_t_mapping(literal('energy manure'),skos:broadMatch,agro:c_25122,ground_truth).%[Energy production]
my_t_mapping(literal('energy saving wegtraffic'),skos:broadMatch,agro:c_2567,ground_truth).%[Energy conservation]
my_t_mapping(literal('Ethanol'),skos:exactMatch,agro:c_10677,ground_truth).%[Ethanol]
my_t_mapping(literal('Ethylene carbohydrates'),skos:broadMatch,agro:c_2679,ground_truth).%[Ethylene]
my_t_mapping(literal('Ethylene carbohydrates/starch'),skos:broadMatch,agro:c_2679,ground_truth).%[Ethylene]
my_t_mapping(literal('Ethylene starch'),skos:broadMatch,agro:c_2679,ground_truth).%[Ethylene]
my_t_mapping(literal('Ethylene wood'),skos:broadMatch,agro:c_2679,ground_truth).%[Ethylene]
my_t_mapping(literal('Europees HVDC grid'),skos:relatedMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Exceedance demand'),skos:relatedMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Export - import'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export Electricity tov demand'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export liquid biofuel tov use'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export natural gas tov natural gas use'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export'),skos:exactMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export/bunkers fossil transportbr.st. tov use'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Export/bunkers'),skos:relatedMatch,agro:c_2761,ground_truth).%[Exports]
my_t_mapping(literal('Extra demand HT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Extra demand LT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Extra demand'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Extra supply HT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Extra supply LT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Extra supply'),skos:relatedMatch,agro:c_25122,ground_truth).%[Energy production]
my_t_mapping(literal('fermentation biomass'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('fermentation carbohydrates'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('fermentation e manure'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('fermentation lignocellulosis'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('fermentation starch'),skos:broadMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('fertilizer Production'),skos:relatedMatch,agro:c_2866,ground_truth).%[Fertilizer industry]
my_t_mapping(literal('Fertilizer'),skos:exactMatch,agro:c_2867,ground_truth).%[fertilizers]
my_t_mapping(literal('fertilizer'),skos:relatedMatch,agro:c_2866,ground_truth).%[Fertilizer industry]
my_t_mapping(literal('Fine-grained grid Hydrogen'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('forest residues'),skos:broadMatch,agro:c_3049,ground_truth).%[Forest products]
my_t_mapping(literal('fossil fuel'),skos:broadMatch,agro:c_3136,ground_truth).%[fuels]
my_t_mapping(literal('fossil plastic (fractie)'),skos:relatedMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('fossil'),skos:broadMatch,agro:c_3136,ground_truth).%[fuels]
my_t_mapping(literal('fraction heaters'),skos:relatedMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('fraction HT heaters'),skos:relatedMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('fraction LT heaters'),skos:relatedMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('fraction SHT heaters'),skos:relatedMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('Fuel cell car'),skos:relatedMatch,agro:c_25778,ground_truth).%[Electric motors]
my_t_mapping(literal('Fuel production'),skos:relatedMatch,agro:c_3136,ground_truth).%[fuels]
my_t_mapping(literal('fuel'),skos:exactMatch,agro:c_3136,ground_truth).%[fuels]
my_t_mapping(literal('gas BTL'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('gas combustion CCS'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('gas combustion STEG CCS'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('gas combustion STEG'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('gas combustion turbine'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('Gas combustion'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('Gas heaters'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('gas NL'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('Gasoline engine'),skos:closeMatch,agro:c_26070,ground_truth).%[Gasoline engines]
my_t_mapping(literal('Geothermal heat'),skos:broadMatch,agro:c_3238,ground_truth).%[Geothermal energy]
my_t_mapping(literal('Geothermal heating WKO'),skos:broadMatch,agro:c_3524,ground_truth).%[Heating]
my_t_mapping(literal('Geothermal heating'),skos:broadMatch,agro:c_3524,ground_truth).%[Heating]
my_t_mapping(literal('GO U'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO WB'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('GO WB'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('GO WN'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO-U LT'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO-U'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO-WB LT'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO-WB'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('GO-WN LT'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('GO-WN'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('GO'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('grass waste'),skos:broadMatch,agro:c_35237,ground_truth).%[Organic wastes]
my_t_mapping(literal('GWP Methane'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Heat demand HT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Heat demand LT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Heat demand SHT'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('heat derden'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('Heat electricity'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('heat electricity'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('Heat HT'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('Heat LT'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('heat production (incl. CHP)'),skos:relatedMatch,agro:c_33072,ground_truth).%[Heat loss during processing]
my_t_mapping(literal('Heat Production'),skos:relatedMatch,agro:c_33072,ground_truth).%[Heat loss during processing]
my_t_mapping(literal('Heat pump groundwater'),skos:broadMatch,agro:c_24398,ground_truth).%[Heat pumps]
my_t_mapping(literal('Heat pump soil'),skos:broadMatch,agro:c_24398,ground_truth).%[Heat pumps]
my_t_mapping(literal('heat pumps gas'),skos:broadMatch,agro:c_24398,ground_truth).%[Heat pumps]
my_t_mapping(literal('Heat SHT'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('heated water network'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Heater biomass'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('Heater coal'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('Heater natural gas'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('heaters H2'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('heaters Hydrogen'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('heatProduction (incl. CHP)'),skos:relatedMatch,agro:c_33072,ground_truth).%[Heat loss during processing]
my_t_mapping(literal('heavy fuel oil'),skos:broadMatch,agro:c_4851,ground_truth).%[mineral oils]
my_t_mapping(literal('heavy fuel oilgasification CCS'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('heavy fuel oilgasification'),skos:broadMatch,agro:c_34000,ground_truth).%[Gasification]
my_t_mapping(literal('Hisarna CCS'),skos:relatedMatch,agro:c_32675,ground_truth).%[Non food industries]
my_t_mapping(literal('hot water network'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works
my_t_mapping(literal('household ref'),skos:relatedMatch,agro:c_3676,ground_truth).%[households]
my_t_mapping(literal('houses existing in 2010 en niet gerenoveerd'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('houses existing in 2010 maar gerenoveerd'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('houses existing met Heat net in 2010'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('Houses existing'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('houses existing'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('houses new na 2010'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('Houses new'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('houses new'),skos:relatedMatch,agro:c_11629,ground_truth).%[Houses]
my_t_mapping(literal('HT heaters biomass CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('HT heaters biomass'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('HT heaters coal CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('HT heaters coal'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('HT heaters gas CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('HT heaters gas'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('hybrid'),skos:broadMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('hydrogen coarse network'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Hydrogen engine'),skos:broadMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('hydrogen fine network'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('hydrogen infrastructure built environment'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Hydrogen'),skos:exactMatch,agro:c_3724,ground_truth).%[Hydrogen]
my_t_mapping(literal('hydrogen'),skos:exactMatch,agro:c_3724,ground_truth).%[Hydrogen]
my_t_mapping(literal('ICE op H2'),skos:broadMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('ICE'),skos:exactMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('Import Electricity tov demand'),skos:broadMatch,agro:c_3815,ground_truth).%[Imports]
my_t_mapping(literal('Import fossil transportbr.st. tov use'),skos:broadMatch,agro:c_3815,ground_truth).%[Imports]
my_t_mapping(literal('Import liquid biofuel tov use'),skos:broadMatch,agro:c_3815,ground_truth).%[Imports]
my_t_mapping(literal('Import natural gas tov natural gas use'),skos:broadMatch,agro:c_3815,ground_truth).%[Imports]
my_t_mapping(literal('Import'),skos:exactMatch,agro:c_3815,ground_truth).%[Imports]
my_t_mapping(literal('Import/export'),skos:relatedMatch,agro:c_10980,ground_truth).%[Foreign trade]
my_t_mapping(literal('in costs'),skos:relatedMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('indirect Emissions outside netherlands'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Individual cars'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('individual cars'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('individual cars+bestel+licht vracht'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('industrial wood waste'),skos:closeMatch,agro:c_28184,ground_truth).%[Waste wood (conversion)]
my_t_mapping(literal('industry Heat'),skos:relatedMatch,agro:c_33072,ground_truth).%[Heat loss during processing]
my_t_mapping(literal('Industry'),skos:relatedMatch,agro:c_3848,ground_truth).%[industry]
my_t_mapping(literal('industry'),skos:relatedMatch,agro:c_3848,ground_truth).%[industry]
my_t_mapping(literal('Infrastructure and methane pumps'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure Electricity Sea'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure en pumps Methane'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure Hydrogen GO'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure liquid fuel'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure need'),skos:relatedMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Infrastructure'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('inland shipping + fishing'),skos:broadMatch,agro:c_31910,ground_truth).%[waterway transport]
my_t_mapping(literal('Input waste'),skos:relatedMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('Inputfactor'),skos:relatedMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('Inputs'),skos:closeMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('Internal combustion engine'),skos:exactMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('Investment'),skos:exactMatch,agro:c_3930,ground_truth).%[investment]
my_t_mapping(literal('Investmentsfactor'),skos:relatedMatch,agro:c_3930,ground_truth).%[investment]
my_t_mapping(literal('kerosene'),skos:exactMatch,agro:c_11961,ground_truth).%[Kerosene]
my_t_mapping(literal('land use'),skos:exactMatch,agro:c_4182,ground_truth).%[land use]
my_t_mapping(literal('Land- en horticulture'),skos:closeMatch,agro:c_3671,ground_truth).%[horticulture]
my_t_mapping(literal('lifetime'),skos:closeMatch,agro:c_358,ground_truth).%[Depreciation]
my_t_mapping(literal('liquid fuel and traffic'),skos:relatedMatch,agro:c_3136,ground_truth).%[liquid fuels]
my_t_mapping(literal('Liquid Fuel'),skos:exactMatch,agro:c_25025,ground_truth).%[liquid fuels]
my_t_mapping(literal('Liquid fuel'),skos:exactMatch,agro:c_25025,ground_truth).%[liquid fuels]
my_t_mapping(literal('liquid fuel'),skos:exactMatch,agro:c_3136,ground_truth).%[liquid fuels]
my_t_mapping(literal('loss in netten %'),skos:broadMatch,agro:c_25309,ground_truth).%[Energy losses]
my_t_mapping(literal('loss in netten'),skos:broadMatch,agro:c_25309,ground_truth).%[Energy losses]
my_t_mapping(literal('LT heaters biomass CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('LT heaters biomass'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('LT heaters coal CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('LT heaters coal'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('LT heaters gas CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('LT heaters gas'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('Mais'),skos:exactMatch,agro:c_12332,ground_truth).%[maize]
my_t_mapping(literal('manure op land'),skos:broadMatch,agro:c_27905,ground_truth).%[Manures(fertilizers)]
my_t_mapping(literal('manure'),skos:exactMatch,agro:c_27905,ground_truth).%[Manures(fertilizers)]
my_t_mapping(literal('manurefactor'),skos:relatedMatch,agro:c_27905,ground_truth).%[Manures(fertilizers)]
my_t_mapping(literal('manurestorage'),skos:broadMatch,agro:c_2803,ground_truth).%[storage]
my_t_mapping(literal('Max. extra supply'),skos:relatedMatch,agro:c_25122,ground_truth).%[Energy production]
my_t_mapping(literal('meat cows'),skos:broadMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('Methane gas'),skos:closeMatch,agro:c_4784,ground_truth).%[Methane]
my_t_mapping(literal('Methane'),skos:exactMatch,agro:c_4784,ground_truth).%[Methane]
my_t_mapping(literal('methane'),skos:exactMatch,agro:c_4784,ground_truth).%[Methane]
my_t_mapping(literal('Methaneopbrengst'),skos:relatedMatch,agro:c_4784,ground_truth).%[Methane]
my_t_mapping(literal('micro-CHP fuel cell'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('micro-CHP'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('Microcar EV'),skos:relatedMatch,agro:c_25778,ground_truth).%[Electric motors]
my_t_mapping(literal('Microcar ICE'),skos:relatedMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('Motorgasoline'),skos:closeMatch,agro:c_11099,ground_truth).%[Gasoline]
my_t_mapping(literal('natural gas foreign'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('natural gas import'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('natural gas Netherlands'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('natural gas netherlands'),skos:broadMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('natural gas vehicle'),skos:relatedMatch,agro:c_25776,ground_truth).%[Internal combustion engines]
my_t_mapping(literal('Natural gas'),skos:exactMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('natural gas'),skos:exactMatch,agro:c_5087,ground_truth).%[Natural gas]
my_t_mapping(literal('netherlands'),skos:exactMatch,agro:c_5142,ground_truth).%[Netherlands]
my_t_mapping(literal('NH3 electricity'),skos:relatedMatch,agro:c_349,ground_truth).%[Ammonia]
my_t_mapping(literal('NH3 gas CCS'),skos:relatedMatch,agro:c_349,ground_truth).%[Ammonia]
my_t_mapping(literal('NH3 gas'),skos:broadMatch,agro:c_349,ground_truth).%[Ammonia]
my_t_mapping(literal('Nuclear power'),skos:closeMatch,agro:c_5252,ground_truth).%[nuclear energy]
my_t_mapping(literal('nuclear power'),skos:closeMatch,agro:c_5252,ground_truth).%[nuclear energy]
my_t_mapping(literal('oil raffinage'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery CCS'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery future CCS'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery future'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery H2'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery hydrogen'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('oil refinery'),skos:broadMatch,agro:c_3074,ground_truth).%[Fractionation]
my_t_mapping(literal('Oil resource'),skos:broadMatch,agro:c_4851,ground_truth).%[Mineral oils]
my_t_mapping(literal('Ondergronds (civiel)'),skos:broadMatch,agro:c_7431,ground_truth).%[Storage structures]
my_t_mapping(literal('Operational costs'),skos:closeMatch,agro:c_28737,ground_truth).%[Operating costs]
my_t_mapping(literal('other (air traffic, shipping en other vehicles)'),skos:broadMatch,agro:c_7874,ground_truth).%[Transport]
my_t_mapping(literal('other animals'),skos:relatedMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('other Emissions Total'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('other greenhouse gas Emissions'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('other sources'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('other vehicles (fuel)'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('other vehicles fuel'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('Outputfactor'),skos:relatedMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('Outputs'),skos:closeMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('outside netherlands'),skos:relatedMatch,agro:c_5142,ground_truth).%[Netherlands]
my_t_mapping(literal('passenger -traffic weg'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('passenger car\'s'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('performance unit'),skos:relatedMatch,agro:c_25788,ground_truth).%[equipment performance]
my_t_mapping(literal('performance'),skos:closeMatch,agro:c_25788,ground_truth).%[equipment performance]
my_t_mapping(literal('pigs'),skos:broadMatch,agro:c_13750,ground_truth).%[livestock raising]
my_t_mapping(literal('Plastic waste'),skos:broadMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('Plastics biomass'),skos:broadMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('Plastics oil'),skos:broadMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('Plastics oil CCS'),skos:broadMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('Plastics via FT CCS biomass'),skos:broadMatch,agro:c_5998,ground_truth).%[Plastics]
my_t_mapping(literal('Plugin fuel cell car'),skos:relatedMatch,agro:c_25778,ground_truth).%[Electric motors]
my_t_mapping(literal('Plugin hybrid'),skos:relatedMatch,agro:c_25778,ground_truth).%[Electric motors]
my_t_mapping(literal('poultry'),skos:closeMatch,agro:c_6148,ground_truth).%[poultry farming]
my_t_mapping(literal('power'),skos:exactMatch,agro:c_13558,ground_truth).%[Power]
my_t_mapping(literal('Process Emissions F gas'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Process Emissions industry other'),skos:relatedMatch,agro:c_330808,ground_truth).%[atmospheric emission]
my_t_mapping(literal('Production fertilizer (ammonia)'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production N-fertilizer (ammonia)'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production plastics oil'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production resource plastics'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production steel'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production voor eigen use'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Production'),skos:exactMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Productioncosts'),skos:exactMatch,agro:c_6202,ground_truth).%[Production costs]
my_t_mapping(literal('Public buildings existing'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('Public buildings'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('public buildings'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('railroad traffic + other electrice vehicles'),skos:broadMatch,agro:c_6434,ground_truth).%[Rail transport]
my_t_mapping(literal('Reference costs'),skos:broadMatch,agro:c_1922,ground_truth).%[Costs]
my_t_mapping(literal('Reference prijzen'),skos:broadMatch,agro:c_6178,ground_truth).%[prices]
my_t_mapping(literal('Reference verbruik'),skos:broadMatch,agro:c_16121,ground_truth).%[Energy consumption]
my_t_mapping(literal('Renewable gas'),skos:broadMatch,agro:c_25719,ground_truth).%[renwable energy]
my_t_mapping(literal('Rente'),skos:relatedMatch,agro:c_3912,ground_truth).%[Interest rates]
my_t_mapping(literal('required inputs'),skos:closeMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('reservoir soil'),skos:broadMatch,agro:c_7431,ground_truth).%[Storage structures]
my_t_mapping(literal('resource coal CCS'),skos:relatedMatch,agro:c_1693,ground_truth).%[Coal]
my_t_mapping(literal('resource coal'),skos:relatedMatch,agro:c_1693,ground_truth).%[Coal]
my_t_mapping(literal('resources'),skos:exactMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('RestHeat in existinge situatie'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('Roof area'),skos:broadMatch,agro:c_35328,ground_truth).%[Surface area]
my_t_mapping(literal('shipping (allocation netherlands)'),skos:broadMatch,agro:c_31910,ground_truth).%[waterway transport]
my_t_mapping(literal('shipping bunkers'),skos:relatedMatch,agro:c_26165,ground_truth).%[Bunker silos]
my_t_mapping(literal('shipping'),skos:closeMatch,agro:c_31910,ground_truth).%[waterway transport]
my_t_mapping(literal('SHT heaters biomass CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('SHT heaters biomass'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('SHT heaters coal CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('SHT heaters coal'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('SHT heaters gas CCS'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('SHT heaters gas'),skos:broadMatch,agro:c_36740,ground_truth).%[Heaters]
my_t_mapping(literal('Small scale biomass combustion'),skos:broadMatch,agro:c_1777,ground_truth).%[Combustion]
my_t_mapping(literal('Smart Grid Decentralized Power generation'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('Smart grid voor decentrale generation'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('SMR CCS'),skos:broadMatch,agro:c_25191,ground_truth).%[chemical reactions]
my_t_mapping(literal('SMR'),skos:broadMatch,agro:c_25191,ground_truth).%[chemical reactions]
my_t_mapping(literal('Solar boiler'),skos:broadMatch,agro:c_28286,ground_truth).%[Boilers]
my_t_mapping(literal('solar PV'),skos:relatedMatch,agro:c_7222,ground_truth).%[Solar energy]
my_t_mapping(literal('solid waste'),skos:exactMatch,agro:c_7228,ground_truth).%[Solid wastes]
my_t_mapping(literal('solide costs'),skos:closeMatch,agro:c_2958,ground_truth).%[Fixed costs]
my_t_mapping(literal('sources outside considered energy system'),skos:broadMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('starch'),skos:exactMatch,agro:c_7369,ground_truth).%[Starch]
my_t_mapping(literal('Steammethane Reforming'),skos:broadMatch,agro:c_25191,ground_truth).%[chemical reactions]
my_t_mapping(literal('steel Production'),skos:broadMatch,agro:c_6200,ground_truth).%[Production]
my_t_mapping(literal('Steel'),skos:broadMatch,agro:c_17746,ground_truth).%[Fabrication]
my_t_mapping(literal('steel'),skos:relatedMatch,agro:c_7384,ground_truth).%[Steel]
my_t_mapping(literal('storage capacity'),skos:relatedMatch,agro:c_7427,ground_truth).%[storage]
my_t_mapping(literal('Suitability type biomass'),skos:relatedMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('supply wind op land'),skos:relatedMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('supply wind op sea'),skos:relatedMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('supply zon-PV'),skos:relatedMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('supply'),skos:relatedMatch,agro:c_25058,ground_truth).%[Power generation]
my_t_mapping(literal('technology choices'),skos:related,agro:c_7644,ground_truth).%[technology]
my_t_mapping(literal('technology name'),skos:related,agro:c_7644,ground_truth).%[technology]
my_t_mapping(literal('technology'),skos:exactMatch,agro:c_7644,ground_truth).%[technology]
my_t_mapping(literal('technologys'),skos:exactMatch,agro:c_7644,ground_truth).%[technology]
my_t_mapping(literal('Third parties heat'),skos:broadMatch,agro:c_31905,ground_truth).%[Thermal energy]
my_t_mapping(literal('Total co fermentation'),skos:relatedMatch,agro:c_2855,ground_truth).%[fermentation]
my_t_mapping(literal('Total demand'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Total mengsel'),skos:broadMatch,agro:c_3136,ground_truth).%[fuels]
my_t_mapping(literal('Total netherlands'),skos:relatedMatch,agro:c_5142,ground_truth).%[Netherlands]
my_t_mapping(literal('traffic en traffic'),skos:exactMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('Traffic'),skos:exactMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('traffic'),skos:exactMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('Transport And Storage CO2'),skos:relatedMatch,agro:c_9613,ground_truth).%[Carbon dioxide fixation]
my_t_mapping(literal('Transport en storage CO2'),skos:relatedMatch,agro:c_9613,ground_truth).%[Carbon dioxide fixation]
my_t_mapping(literal('Transport'),skos:exactMatch,agro:c_7874,ground_truth).%[Transport]
my_t_mapping(literal('Trucking weg'),skos:closeMatch,agro:c_6620,ground_truth).%[Road transport]
my_t_mapping(literal('Trucking'),skos:closeMatch,agro:c_6620,ground_truth).%[Road transport]
my_t_mapping(literal('trucking'),skos:closeMatch,agro:c_6620,ground_truth).%[Road transport]
my_t_mapping(literal('Uitgangsdemand'),skos:broadMatch,agro:c_9000047,ground_truth).%[Energy demand]
my_t_mapping(literal('Uranium'),skos:exactMatch,agro:c_8084,ground_truth).%[Uranium]
my_t_mapping(literal('uranium'),skos:exactMatch,agro:c_8084,ground_truth).%[Uranium]
my_t_mapping(literal('urban traffic'),skos:broadMatch,agro:c_37947,ground_truth).%[Traffic]
my_t_mapping(literal('usage biomass specifiek'),skos:relatedMatch,agro:c_50146,ground_truth).%[renewable bioresources]
my_t_mapping(literal('usage van resources/energy carriers'),skos:relatedMatch,agro:c_9001017,ground_truth).%[resources]
my_t_mapping(literal('utility buildings in 2010 (HDO)'),skos:relatedMatch,agro:c_1142,ground_truth).%[Buildings]
my_t_mapping(literal('Variabele costs'),skos:broadMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('Variabele costsfactor'),skos:relatedMatch,agro:c_1922,ground_truth).%[costs]
my_t_mapping(literal('vegetable oil'),skos:exactMatch,agro:c_24270,ground_truth).%[vegetable oils]
my_t_mapping(literal('Versterking Electricity grid'),skos:broadMatch,agro:c_26790,ground_truth).%[Public works]
my_t_mapping(literal('waste bio'),skos:closeMatch,agro:c_35237,ground_truth).%[Organic wastes]
my_t_mapping(literal('Waste disposal'),skos:exactMatch,agro:c_8305,ground_truth).%[  Waste disposal]
my_t_mapping(literal('waste niet bio'),skos:broadMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('waste oil'),skos:broadMatch,agro:c_35237,ground_truth).%[Organic wastes]
my_t_mapping(literal('waste stort'),skos:broadMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('waste Total'),skos:relatedMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('waste voor combustion'),skos:broadMatch,agro:c_8307,ground_truth).%[wastes]
my_t_mapping(literal('wet organic waste'),skos:broadMatch,agro:c_35237,ground_truth).%[Organic wastes]
my_t_mapping(literal('Wind energy land'),skos:broadMatch,agro:c_37929,ground_truth).%[Wind energy]
my_t_mapping(literal('Wind energy sea'),skos:broadMatch,agro:c_37929,ground_truth).%[Wind energy]
my_t_mapping(literal('WKK biomass liquid CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKK biomass liquid'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKK biomass solid CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKK biomass solid'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKK gas CCS'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKK gas'),skos:broadMatch,agro:c_37873,ground_truth).%[Energy technology]
my_t_mapping(literal('WKO heat pump'),skos:broadMatch,agro:c_24398,ground_truth).%[Heat pumps]
my_u_mapping(literal('% efficiency'),skos:exactMatch,om:percent,ground_truth).%[]
my_u_mapping(literal('1000 operating hours'),skos:closeMatch,om:hour,ground_truth).%[]
my_u_mapping(literal('billion km'),skos:closeMatch,om:kilometre,ground_truth).%[]
my_u_mapping(literal('GJ'),skos:exactMatch,om:gigajoule,ground_truth).%[]
my_u_mapping(literal('GW'),skos:exactMatch,om:gigawatt,ground_truth).%[]
my_u_mapping(literal('GWh'),skos:relatedMatch,om:kilowatt_hour,ground_truth).%[]
my_u_mapping(literal('kg CO2-eq'),skos:closeMatch,om:kilogram,ground_truth).%[]
my_u_mapping(literal('kW'),skos:exactMatch,om:kilowatt,ground_truth).%[]
my_u_mapping(literal('million aansluit.'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('million car\'s'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('million m2'),skos:closeMatch,om:square_metre,ground_truth).%[]
my_u_mapping(literal('million'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('MJ/kg'),skos:relatedMatch,om:joule_per_kilogram,ground_truth).%[]
my_u_mapping(literal('Mtonne ammonia'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne CO2 eq'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne CO2-eq'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne CO2'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne CO2/eq'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne etheen'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne NH3'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne plastic'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne steel'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne/million animals'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('Mtonne/PJ'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('MW'),skos:exactMatch,om:megawatt,ground_truth).%[]
my_u_mapping(literal('MW/GWh'),skos:relatedMatch,om:megawatt,ground_truth).%[]
my_u_mapping(literal('number animals'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('number huizen'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('number'),skos:closeMatch,om:one,ground_truth).%[]
my_u_mapping(literal('operating hours'),skos:closeMatch,om:hour,ground_truth).%[]
my_u_mapping(literal('per PJ H2'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ *'),skos:exactMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ fuel'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ H2'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ Heat'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ'),skos:exactMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ/Mtonne'),skos:relatedMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('tonne'),skos:exactMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('tonne/animal'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('tonneCH4/Mt manure'),skos:relatedMatch,om:tonne,ground_truth).%[]
my_u_mapping(literal('TWh capacity'),skos:relatedMatch,om:kilowatt_hour,ground_truth).%[]
my_u_mapping(literal('TWh'),skos:relatedMatch,om:kilowatt_hour,ground_truth).%[]
my_u_mapping(literal('year'),skos:exactMatch,om:year,ground_truth).%[]
my_u_mapping(literal('%'),skos:exactMatch,om:percent,ground_truth).%[]
my_u_mapping(literal('kg'),skos:exactMatch,om:kilogram,ground_truth).%[]
my_u_mapping(literal('km2'),skos:exactMatch,om:square_kilometre).%[]
my_u_mapping(literal('m2'),skos:exactMatch,om:square_metre,ground_truth).%[]
my_u_mapping(literal('MJ'),skos:exactMatch,om:megajoule,ground_truth).%[]
my_u_mapping(literal('per day'),skos:closeMatch,om:day,ground_truth).%[]
my_u_mapping(literal('PJ max'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('PJ maximum'),skos:closeMatch,om:petajoule,ground_truth).%[]
my_u_mapping(literal('trucking km'),skos:closeMatch,om:kilometre,ground_truth).%[]
